name: hux
description: an open-source state of the art UI library for Flutter 💙
version: 0.1.3
homepage: https://github.com/zoeglbrt/hux
repository: https://github.com/zoeglbrt/hux
issue_tracker: https://github.com/zoeglbrt/hux/issues
documentation: https://github.com/zoeglbrt/hux#readme

# Topics help users find your package
topics:
  - ui
  - widgets
  - components
  - theme
  - design-system
  - material-design
  - buttons
  - cards
  - charts
  - loading
  - text-field
  - dark-mode
  - responsive

# Screenshots displayed on pub.dev
screenshots:
  - description: 'HuxButton component variants'
    path: screenshots/hux-buttons.png
  - description: 'HuxCard with different configurations'
    path: screenshots/hux-cards.png
  - description: 'HuxTextField input component'
    path: screenshots/hux-text-field.png
  - description: 'HuxLoading indicators'
    path: screenshots/hux-loading.png
  - description: 'HuxChart data visualization'
    path: screenshots/hux-charts.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_feather_icons: ^2.0.0+1
  cristalyse: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Explicitly declare platform support including WASM
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter: 