name: hux
description: A modern Flutter UI package with beautiful, customizable components
version: 0.1.1
homepage: https://github.com/zoeglbrt/hux
repository: https://github.com/zoeglbrt/hux

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_feather_icons: ^2.0.0+1
  cristalyse: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Explicitly declare platform support including WASM
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter: 